<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DealershipTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('dealership')->insert([
            [
                'model' => 'X5',
                'brand' => 'BMW',
                'engine' => '3.0L Turbo I6',
                'power' => '335 hp',
                'price' => 61000.00,
                'year' => 2024,
                'image_path' => 'BMW-X5-2024.jpg',
                'model_3d' => 'ruta_al_modelo_3d.glb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'model' => 'Model Y',
                'brand' => 'Tesla',
                'engine' => 'Dual Motor Electric',
                'power' => '384 hp',
                'price' => 53990.00,
                'year' => 2025,
                'image_path' => 'Tesla_Model_Y_2024.jpg',
                'model_3d' => 'ruta_al_modelo_3d.glb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'model' => 'A6',
                'brand' => 'Audi',
                'engine' => '2.0L Turbo I4',
                'power' => '261 hp',
                'price' => 58000.00,
                'year' => 2024,
                'image_path' => 'audi_a6.jpg',
                'model_3d' => 'ruta_al_modelo_3d.glb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'model' => 'C-Class',
                'brand' => 'Mercedes-Benz',
                'engine' => '2.0L Turbo I4 Mild Hybrid',
                'power' => '255 hp',
                'price' => 48000.00,
                'year' => 2023,
                'image_path' => 'mercedes_c_class.jpg',
                'model_3d' => 'ruta_al_modelo_3d.glb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'model' => 'Camry',
                'brand' => 'Toyota',
                'engine' => '2.5L I4 Hybrid',
                'power' => '208 hp',
                'price' => 31000.00,
                'year' => 2024,
                'image_path' => 'toyota_camry.jpg',
                'model_3d' => 'ruta_al_modelo_3d.glb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'model' => 'Civic',
                'brand' => 'Honda',
                'engine' => '1.5L Turbo I4',
                'power' => '180 hp',
                'price' => 25000.00,
                'year' => 2023,
                'image_path' => 'honda_civic.jpg',
                'model_3d' => 'ruta_al_modelo_3d.glb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'model' => 'Mustang GT',
                'brand' => 'Ford',
                'engine' => '5.0L V8',
                'power' => '480 hp',
                'price' => 55000.00,
                'year' => 2024,
                'image_path' => 'ford_mustang_gt.jpg',
                'model_3d' => 'ruta_al_modelo_3d.glb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'model' => 'Corvette Stingray',
                'brand' => 'Chevrolet',
                'engine' => '6.2L V8',
                'power' => '490 hp',
                'price' => 67000.00,
                'year' => 2025,
                'image_path' => 'chevrolet_corvette_stingray.jpg',
                'model_3d' => 'ruta_al_modelo_3d.glb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'model' => 'CX-90',
                'brand' => 'Mazda',
                'engine' => '3.3L Turbo I6 Hybrid',
                'power' => '340 hp',
                'price' => 49000.00,
                'year' => 2024,
                'image_path' => 'mazda_cx90.jpg',
                'model_3d' => 'ruta_al_modelo_3d.glb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'model' => 'Outback',
                'brand' => 'Subaru',
                'engine' => '2.4L Turbo Boxer',
                'power' => '260 hp',
                'price' => 39000.00,
                'year' => 2023,
                'image_path' => 'subaru_outback.jpg',
                'model_3d' => 'ruta_al_modelo_3d.glb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'model' => 'Rogue',
                'brand' => 'Nissan',
                'engine' => '1.5L Turbo I3',
                'power' => '201 hp',
                'price' => 32000.00,
                'year' => 2024,
                'image_path' => 'nissan_rogue.jpg',
                'model_3d' => 'ruta_al_modelo_3d.glb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'model' => 'Velar',
                'brand' => 'Land Rover',
                'engine' => '3.0L Turbo I6 Mild Hybrid',
                'power' => '395 hp',
                'price' => 67000.00,
                'year' => 2024,
                'image_path' => 'landrover_velar.jpg',
                'model_3d' => 'ruta_al_modelo_3d.glb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'model' => '911 Carrera',
                'brand' => 'Porsche',
                'engine' => '3.0L Twin-Turbo Flat-6',
                'power' => '379 hp',
                'price' => 106000.00,
                'year' => 2025,
                'image_path' => 'porsche_911_carrera.jpg',
                'model_3d' => 'ruta_al_modelo_3d.glb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'model' => 'Kona Electric',
                'brand' => 'Hyundai',
                'engine' => 'Electric 64.8 kWh',
                'power' => '201 hp',
                'price' => 37000.00,
                'year' => 2024,
                'image_path' => 'hyundai_kona_electric.jpg',
                'model_3d' => 'ruta_al_modelo_3d.glb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'model' => 'XC60',
                'brand' => 'Volvo',
                'engine' => '2.0L Turbo I4 Plug-in Hybrid',
                'power' => '455 hp',
                'price' => 58000.00,
                'year' => 2025,
                'image_path' => 'volvo_xc60.jpg',
                'model_3d' => 'ruta_al_modelo_3d.glb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'model' => 'Stelvio',
                'brand' => 'Alfa Romeo',
                'engine' => '2.0L Turbo I4',
                'power' => '280 hp',
                'price' => 47000.00,
                'year' => 2024,
                'image_path' => 'alfa_stelvio.jpg',
                'model_3d' => 'ruta_al_modelo_3d.glb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'model' => 'Taycan 4S',
                'brand' => 'Porsche',
                'engine' => 'Dual Motor Electric',
                'power' => '522 hp',
                'price' => 111000.00,
                'year' => 2025,
                'image_path' => 'porsche_taycan_4s.jpg',
                'model_3d' => 'ruta_al_modelo_3d.glb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'model' => 'Q5',
                'brand' => 'Audi',
                'engine' => '2.0L Turbo I4',
                'power' => '261 hp',
                'price' => 47000.00,
                'year' => 2024,
                'image_path' => 'audi_q5.jpg',
                'model_3d' => 'ruta_al_modelo_3d.glb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'model' => 'RAV4',
                'brand' => 'Toyota',
                'engine' => '2.5L Hybrid I4',
                'power' => '219 hp',
                'price' => 34000.00,
                'year' => 2024,
                'image_path' => 'toyota_rav4.jpg',
                'model_3d' => 'ruta_al_modelo_3d.glb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'model' => 'F-150 Lightning',
                'brand' => 'Ford',
                'engine' => 'Dual Motor Electric',
                'power' => '580 hp',
                'price' => 67000.00,
                'year' => 2025,
                'image_path' => 'ford_f150_lightning.jpg',
                'model_3d' => 'ruta_al_modelo_3d.glb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'model' => 'reguera',
                'brand' => 'Koniseeg',
                'engine' => 'Motor Central v12',
                'power' => '1900 hp',
                'price' => 3000000.00,
                'year' => 2025,
                'image_path' => 'KoenigseggRegera.jpg',
                'model_3d' => 'koenigsegg_one-1.glb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
